# Generated by Django 2.0.3 on 2018-03-11 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccomodationArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('edited', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('blocked', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('edited', models.DateTimeField(auto_now_add=True)),
                ('rack', models.CharField(max_length=3)),
                ('tier', models.CharField(max_length=3)),
                ('position', models.CharField(max_length=3)),
                ('blocked', models.BooleanField(default=False)),
                ('accomodation_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.AccomodationArea')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SelectionArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('edited', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('blocked', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('edited', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('blocked', models.BooleanField(default=False)),
                ('address_code_separator', models.CharField(max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cell',
            name='selection_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.SelectionArea'),
        ),
        migrations.AddField(
            model_name='cell',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Warehouse'),
        ),
    ]
