# Generated by Django 2.0.3 on 2018-03-11 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomodationarea',
            name='created',
        ),
        migrations.RemoveField(
            model_name='accomodationarea',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='created',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='selectionarea',
            name='created',
        ),
        migrations.RemoveField(
            model_name='selectionarea',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='created',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='edited',
        ),
    ]
