# Generated by Django 2.0.3 on 2018-03-11 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20180311_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('blocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='work_zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.WorkZone'),
        ),
    ]
