# Generated by Django 2.0.3 on 2018-03-20 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0003_auto_20180311_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'permissions': (('view_warehouse', 'Для вас не доступен склад'),)},
        ),
        migrations.AddField(
            model_name='warehouse',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
