# Generated by Django 2.0.3 on 2018-03-20 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_auto_20180320_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='owner',
        ),
    ]
